### ISSUE TITLE
catch discord errors and restart the listener

### ISSUE THREAD

**Issue by lagleki** [lagleki/Lojban-1Chat-Bridge#42]
```
events.js:173
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Client.emit (events.js:171:17)
    at WebSocketConnection.onError (/home/gleki/Lojban-1Chat-Bridge/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:374:17)
    at WebSocket.onError (/home/gleki/Lojban-1Chat-Bridge/node_modules/discord.js/node_modules/ws/lib/event-target.js:128:16)
    at WebSocket.emit (events.js:182:13)
    at _receiver.cleanup (/home/gleki/Lojban-1Chat-Bridge/node_modules/discord.js/node_modules/ws/lib/websocket.js:211:14)
    at Receiver.cleanup (/home/gleki/Lojban-1Chat-Bridge/node_modules/discord.js/node_modules/ws/lib/receiver.js:557:13)
    at WebSocket.finalize (/home/gleki/Lojban-1Chat-Bridge/node_modules/discord.js/node_modules/ws/lib/websocket.js:206:20)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by lagleki** [comment]
can no longer confirm
